ALTER TABLE "user_settings" ALTER COLUMN "app_emoji" TYPE VARCHAR(100);

ALTER TABLE "board" ALTER COLUMN "emoji" TYPE VARCHAR(100);

ALTER TABLE "board_column" ALTER COLUMN "emoji" TYPE VARCHAR(100);

ALTER TABLE "links" ALTER COLUMN "emoji" TYPE VARCHAR(100);